repos:
  - repo: local
    hooks:
      - id: clear-jupyter-notebook
        name: Clean notebook
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --ClearMetadataPreprocessor.enabled=True --to=notebook --inplace
        language: system
        files: \.ipynb$
        types: [jupyter]
