repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the latest version
    hooks:
      - id: jupyter-notebook-cleanup
        args: ["--clear-output", "--clear-metadata"]
